
execfile("copy_files.py")
execfile("players_16.py")
execfile("new_players_16.py")
execfile("teams_16.py")
execfile("new_teams_16.py")
execfile("tpl_16.py")
execfile("add_formations.py")
execfile("form16.py")
execfile("new_kits16.py")
execfile("kits_upd.py")
execfile("leagues.py")
execfile("ltl.py")
execfile("loans.py")
execfile("managers.py")
execfile("playernames.py")
