
execfile("copy_files.py")
execfile("playernames.py")
#execfile("add_dtd.py")
#execfile("add_dts.py")
execfile("add_formations.py")
#execfile("add_kits.py")
#execfile("add_leagues.py")
#execfile("add_ltl.py")
execfile("add_players.py")
execfile("add_teams.py")
execfile("add_tpl.py")
#execfile("dtd.py")
#execfile("dts.py")
execfile("form.py")
#execfile("kits.py")
#execfile("leagues.py")
#execfile("ltl.py")
execfile("players.py")
execfile("teams.py")
execfile("tpl.py")
#execfile("new_teams.py")
# execfile("new_kits.py")
#execfile("new_players.py")

